name: Django CI/CD

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "Navigating to project directory..."
            cd /home/ubuntu/student_project-django/student_project_django/Student_project || exit 1

            echo "Updating system packages..."
            sudo apt-get update
            sudo apt-get install -y python3-venv

            echo "Setting up virtual environment..."
            [ ! -d env ] && python3 -m venv env
            source env/bin/activate

            echo "Pulling latest changes from GitHub..."
            git pull origin main

            echo "Installing Python dependencies..."
            pip install --upgrade pip
            pip install django-countries
            pip install -r requirements.txt

            echo "Running database migrations..."
            python manage.py migrate --noinput

            echo "Collecting static files..."
            python manage.py collectstatic --noinput

            echo "Restarting Gunicorn..."
            pkill gunicorn || true
            nohup gunicorn --workers 3 --bind unix:/tmp/gunicorn.sock Student_project.wsgi:application > gunicorn.log 2>&1 &

            echo "Setting socket permissions..."
            sudo chown www-data:www-data /tmp/gunicorn.sock
            sudo chmod 660 /tmp/gunicorn.sock

            echo "Restarting Nginx..."
            sudo systemctl restart nginx

